### ISSUE TITLE
Properties resolution

### ISSUE THREAD

**Issue by danielholgate** [marklogic/ml-gradle#514]
I have an existing project which is being ported from Roxy, and large sets of roles are created per country in the following way. Example:
**gradle.properties** has these properties:
```
country=uk
appuser-name=app-${country}-main
my-role=${appuser-name}-my-role
..many other roles building on $country and $appuser-name etc
```
There is then a role to be deployed which looks like this:
```
<role-properties xmlns="http://marklogic.com/manage">
  <role-name>%%my-role%%</role-name>
  <description>Role for country %%country%%</description>
  <roles/>
  <privileges></privileges>
</role-properties>
```

I expected %%my-role%% to resolve to "uk-main-my-role" before it gets pushed to ML but I can see with --debug that ml-gradle is trying to deploy the role with name "${appuser-name}-my-role" which is an invalid role name and it fails. So it seems it does not fully resolve properties built from other properties before deploy.

<description> however correctly resolves to "Role for country uk" 

Can gradle do this full resolution of properties which are defined with other properties?

**Comment by danielholgate** [comment]
This is core ml-gradle and appears it is not possible to reference other properties like this. Will need to build a custom task to perform the logic to build the final property values

**Comment by rjrudin** [comment]
Here's a recommendation from one of the Gradle developers on how to support this - https://stackoverflow.com/questions/23853044/does-gradle-support-properties-interpolation
