### ISSUE TITLE
Use privileges over roles in security scaffolding

### ISSUE THREAD

**Issue by dmcassel** [marklogic/ml-gradle#546]
**Describe the RFE**
 
[Exercising Privilege to Restrict Content](https://www.marklogic.com/blog/exercising-privilege-to-restrict-content/) talks about using privileges (like http://marklogic.com/xdmp/privileges/rest-reader) over roles (like rest-reader). I believe that's generally accepted guidance. Assuming so, I propose changing ml-gradle's scaffolding to set up the default roles to use privileges over roles.

**Comment by grtjn** [comment]
I think the title of this issue got it backwards.. :)

**Comment by dmcassel** [comment]
You're right, @grtjn! fixed

**Comment by rjrudin** [comment]
Removing from 4.3, but will get to this some day. PR would be appreciated!

**Comment by grtjn** [comment]
I'm short of spare time at the moment, but who knows. Do you have pointers to relevant code?

**Comment by rjrudin** [comment]
I like doing this, as privileges really are the way to go. Can rethink the generated roles as well. No possibility for a breaking change here as the files are generated and then a user is free to modify them however they see fit.

**Comment by rjrudin** [comment]
See https://github.com/marklogic/ml-app-deployer/pull/490
