### ISSUE TITLE
Issue with Specifying Relative Module Paths in build.gradle

### ISSUE THREAD

**Issue by ravichoudhary1993** [marklogic/ml-gradle#673]
ml-gradle version: 4.1.0
Gradle wrapper version: 6.7
MarkLogic version: 10.0.9.4

I'm running Gradle on a local Windows 11 machine.
In the build.gradle file,
I added modulesPath.add("/src/test/unit") in the mlAppConfig block.

Here are the details of the issue:

When checking the logs, it appears that Gradle is taking the path C:\Users\ravichoudhary\.gradle\daemon\6.7\src\test\unit, even though I specified "/src/test/unit" as the module path.

 I've also tried  "./src/test/unit", "src\\test\\unit", and "src\\test\\unit", but they didn't work.

However, when I added the absolute path "D:\\Project\\mlcode\\src\\test\\unit", it worked as expected. The issue seems to be specific to my local system because it's working on another Windows agent.

I expect that specifying "/src/test/unit" as the module path should work, but it's not working as intended on my local system.

**Comment by hansenmc** [comment]
It seems that it's trying to resolve relative paths from the daemon path.

Does it work if you disable the daemon with `--no-daemon`?
https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:disabling_the_daemon

There may be areas of ml-gradle that need to adjust how `Path` is resolved
https://discuss.gradle.org/t/weird-behaviour-of-relative-path-objects-in-daemon-mode/19987/2 
> For the record - if someone encounters this on Windows - getting an absolute path from a relative path works fine via an instance of the `File` class (which is what `Project.file()` returns). The same is not true for instances of the `Path` class.

**Comment by rjrudin** [comment]
Closing due to lack of response - please add a comment though if the above solution does not work for you.
