### ISSUE TITLE
Feature request - append for mlBundle

### ISSUE THREAD

**Issue by DavidEnnis-CleverLlamas** [marklogic/ml-gradle#675]
Referring to this document:

https://github.com/marklogic/ml-gradle/wiki/Bundles

The items are always pre-pended to the configurations - making them get executed first.  However, there may be times in which one would want to use a bundle to change a default behavior. Example: replace an xQuery module to change how something was implemented.

It would be nice if, via configuration, the choice could be made between prepend and append

**Comment by DavidEnnis-17llamas** [comment]
Good point - just force it to append again.  This would make sense for modules.  However, I'd be curious about the overhead of ml-config.

Will play around with this soon.  Trying to see how far I can take using a bundle for various combined-code and config requirements

**Comment by rjrudin** [comment]
It should work for ml-config as well - ml-gradle will merge the resource files together, with the last directory in the list "winning" and overwriting any keys already present in the merged JSON object.

**Comment by DavidEnnis-17llamas** [comment]
Hi ROb.  Yes this is all working fine from what I can see.

**Comment by rjrudin** [comment]
Closing as I believe this request was addressed, but please reopen if that is not the case.
