### ISSUE TITLE
username required on mlInit

### ISSUE THREAD

**Issue by kgmanuel** [marklogic/ml-gradle#688]
**Describe the bug**
At version 4.3.4, mlinit never required a username to be supplied. At 4.7.0, it now ends up with this error message:
```
Unable to connect to MarkLogic app server at http://localhost:8001; cause: username must be of type String
```

**To Reproduce**
1. create a build.gradle file with the following content:
```
plugins {
  id "com.marklogic.ml-gradle" version "4.7.0"
}
```
2. run the mlInit command on a new install:
```
gradle mlInit -PmlHost=localhost
```

**Expected behavior**
complete, i.e. end up with Build Successful

**Comment by rjrudin** [comment]
The reason for this is covered in the 4.5.0 release notes - https://github.com/marklogic/ml-gradle/releases/tag/4.5.0 . All tasks now require `mlUsername` and `mlPassword` to be specified, as those no longer default to values of "admin" (which has long been a bad security practice).

**Comment by rjrudin** [comment]
@kgmanuel https://docs.marklogic.com/REST/POST/admin/v1/init states that it's possible to call the `init` endpoint without any authentication if no authentication has been setup. Was that the case in your test, or had you already configured authentication for MarkLogic?

**Comment by kgmanuel** [comment]
@rjrudin i was just about to post the details of the function docs. This is a fresh install of a marklogic cluster. i don't think init would be used/useable on an already configured instance. 

I think the same applies for [/admin/v1/instance-admin](https://docs.marklogic.com/REST/POST/admin/v1/instance-admin). the equivalent task is mlInstallAdmin. And this task uses a different set of input, i.e. mlAdminUsername and mlAdminPassword. Hence, mlUsername and mlPassword should also not be required.
